common:
    masterDB:
        url: 127.0.00.1
        port: 3306
        userName: root
        password: root
    sqlServer:
        url: 10.20.11.254
        port: 1433
        userName: sa
        password: p@ssw0rd
        database: DC
    netsuite:
        url: odbcserver.na2.netsuite.com
        port: 1708
        userName: DataMigration@meorient.com
        password: "@^*gLGyGCp"
    jedis:
        hosts:
           host_1: 127.0.0.1:6379
    sysConfig: 
        cfgResAndSessionParam: #资源与session参数
            sessionExp: 7200 #session过期时长,单位：分钟
            resRootUrl: #图片等资源存放站点根目录
            releaseMode: false #是否发布模式
            authTimeLimit: 5 #签名验证超时时间限制 单位：分钟
spring:
    profiles:
        active: uat
    freemarker:
        checkTemplateLocation: false
    application:
        name: phonecall
    session:
        store-type: none #redis
    devtools:
        restart:
            exclude: static/**
masterDB:
    dbCfg:
        druidDBCfg:
            driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            url: jdbc:log4jdbc:mysql://${common.masterDB.url}:${common.masterDB.port}/data_center?characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
            username: ${common.masterDB.userName}
            password: ${common.masterDB.password}
            initialSize: 1 # 启动时初始化的创建的连接个数
            maxActive: 50 #可以在池中保持空闲的最大连接数，超出设置值之外的空闲连接将被回收，如设置为-1不限制
            minIdle: 5 #可以在池中保持空闲的最小连接数，超出设置值之外的空闲连接将被创建，如设置为0不创建
            maxWait: 10000 # 如果没有可用连接,在抛出异常前等待的一个连接被归还的最大毫秒数，设置为-1， 设为-1无限制
            removeAbandonedTimeout: 180 # 已抛弃的连接可以被移除的超时时间，单位为秒
            removeAbandoned: true #超过removeAbandonedTimeout时间后，进行已抛弃的回收
            timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
            validationQuery: SELECT 1 FROM DUAL  #用来检测连接是否有效的sql，要求是一个查询语句
            testWhileIdle: false  #申请连接的时候检测
            testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
            testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
            poolPreparedStatements: true #打开PSCache，并且指定每个连接上PSCache的大小
            maxOpenPreparedStatements: 50 #打开PSCache，并且指定每个连接上PSCache的大小
            filters: stat # 属性类型是字符串，常用插件有:监控统计filter:stat、 日志filter:log4j、 防御SQL注入filter:wall
        txAttributes: #参考TransactionAttributeEditor.setAsText()
            "add*": "PROPAGATION_REQUIRED,-Exception"
            "insert*": "PROPAGATION_REQUIRED,-Exception"
            "save*": "PROPAGATION_REQUIRED,-Exception"
            "update*": "PROPAGATION_REQUIRED,-Exception"
            "delete*": "PROPAGATION_REQUIRED,-Exception"
            "*": "readOnly"
        manageMethod: "execution(* com.meorient.phonecall.*.*.service.*.*(..))"
        configLocation: classpath:config/SqlMapConfig.xml
        mapperLocations: classpath*:com/meorient/sqlmap/*.xml
